#!/usr/bin/env node
// Stamps FIREBASE_* values into admin/js/config/firebaseConfig.js from the
// .template.js next to it. Values come from real process.env first (how
// Netlify's build environment supplies them, set via site env vars) and
// fall back to parsing a local .env file for development, since this
// project has no bundler otherwise to inject them.
// Wired as netlify.toml's build command, so every deploy regenerates it.
// Run manually (`node scripts/build-config.js`) after editing .env locally.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const templatePath = path.join(root, 'admin/js/config/firebaseConfig.template.js');
const outPath = path.join(root, 'admin/js/config/firebaseConfig.js');

function parseEnvFile(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq === -1) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

const required = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID',
];

const fromFile = fs.existsSync(envPath) ? parseEnvFile(fs.readFileSync(envPath, 'utf8')) : {};
const env = {};
for (const k of required) env[k] = process.env[k] || fromFile[k];

const missing = required.filter((k) => !env[k]);
if (missing.length) {
  console.error('Missing FIREBASE_* values: ' + missing.join(', ') +
    '\nSet them as real environment variables (e.g. Netlify site env vars) or in a local .env (see .env.example).');
  process.exit(1);
}

let out = fs.readFileSync(templatePath, 'utf8');
for (const k of required) out = out.replaceAll('__' + k + '__', env[k]);
out = '// GENERATED by scripts/build-config.js — do not edit directly, do not commit.\n' + out;

fs.writeFileSync(outPath, out);
console.log('Wrote ' + path.relative(root, outPath));
