#!/usr/bin/env node
// Reads .env and stamps its FIREBASE_* values into
// public/admin/js/config/firebaseConfig.js from the .template.js next to it.
// Run manually after editing .env; also wired as firebase.json's hosting
// predeploy hook so `firebase deploy` always regenerates it first.
// No npm dependencies — this project has no build step otherwise, so a
// bare Node script is the smallest thing that keeps the real config out of
// version control while still letting the static site read it at runtime.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const templatePath = path.join(root, 'public/admin/js/config/firebaseConfig.template.js');
const outPath = path.join(root, 'public/admin/js/config/firebaseConfig.js');

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq === -1) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

if (!fs.existsSync(envPath)) {
  console.error('Missing .env — copy .env.example to .env and fill in the FIREBASE_* values first.');
  process.exit(1);
}
const env = parseEnv(fs.readFileSync(envPath, 'utf8'));

const required = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID',
];
const missing = required.filter((k) => !env[k]);
if (missing.length) {
  console.error('Missing values in .env: ' + missing.join(', '));
  process.exit(1);
}

let out = fs.readFileSync(templatePath, 'utf8');
out = out
  .replace('__FIREBASE_API_KEY__', env.FIREBASE_API_KEY)
  .replace('__FIREBASE_AUTH_DOMAIN__', env.FIREBASE_AUTH_DOMAIN)
  .replace('__FIREBASE_DATABASE_URL__', env.FIREBASE_DATABASE_URL)
  .replace('__FIREBASE_PROJECT_ID__', env.FIREBASE_PROJECT_ID)
  .replace('__FIREBASE_STORAGE_BUCKET__', env.FIREBASE_STORAGE_BUCKET)
  .replace('__FIREBASE_MESSAGING_SENDER_ID__', env.FIREBASE_MESSAGING_SENDER_ID)
  .replace('__FIREBASE_APP_ID__', env.FIREBASE_APP_ID);
out = '// GENERATED by scripts/build-config.js from .env — do not edit directly, do not commit.\n' + out;

fs.writeFileSync(outPath, out);
console.log('Wrote ' + path.relative(root, outPath));
